#logging:
#    level:
#        org:
#            hibernate:
#                SQL: DEBUG
#                type: TRACE
#spring:
#    datasource:
#        password: root
#        url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#        username: root
#    jpa:
#        hibernate:
#            ddl-auto: update
#        properties:
#            hibernate:
#                dialect: org.hibernate.dialect.MySQL5InnoDBDialect

spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: password
    url: jdbc:h2:mem:dev
    username: sa
  jpa:
    show-sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.sql: DEBUG